package V36_Collection_FrameWork.Map_Interface.ConcurrentHashMap;

import java.util.concurrent.ConcurrentSkipListMap;

/*
 * If we required Map which stores the elements in sorted order as well as thread safe then we have to use the ConcurrentSkipListHashMap
 * data or elements are stored in SkipList datastructure.
 * 
 * REVISING CONCEPTS : 
 * 				HASHMAP IS INTERNALLY USES THE ARRAYS TO STORE THE DATA.
 * 				TREEMAP IS INTERNALLY USES THE REDBLACK TREE TO STORE THE COLLISION PART DATA.
 * 				HARE ConcurrentSkipLisrMap WILL STORES THE DATA INTO THE SKIPLIST DATASTRUCTURE.
 * WE CAN CALL ConcurrentSkipLisrMap AS THREAD SAFE TREE MAP AS ITS PROVIDING THE THREAD SAFE ALONG WITH SORTED ELEMENTS
 * 
 * WHAT IS SKIPLIST DATASTRUCTURE?
 * ANS : PROBABILISTIC DATA STRUCTURE : THAT ALLOWS FOR EFFICIENT SEARCH, INSERTION AND DELETION OPERATIONS.
 * 		 IT IS SIMILAR TO THE A SORTED LINKED LIST BUT WITH MULTIPLE LAYERS THAT "SKIP" OVER PORTIONS OF THE LIST TO PROVIDE FASTER ACCESS TO ELEMENTS. 
 * 		 AS ITS HAVE SORTED, MULTI LAYERSED SO DUE TO THIS ACCESS IS FASTER.
 * 
 * 
 * BASICALLY HERE IN THE SKIPLIST DATA STORED IN LAYER AS LIKE BELOW EXAMPLE : 
 * LIST : 1, 2, 3, 4, 5, 6, 7, 8, 9
 * 
 * SKIPLIST LAYERS OF LINKEDLIST: 
 * 
 * LAYER 1 : 1, 2, 3, 4, 5, 6, 7, 8, 9
 * LAYER 2 : 1, 3, 5, 7, 9 //HERE SKIPPED ONE ELEMENT AFTER ONE.
 * LAYER 3 : 1, 5, 9 //HERE SKIPPED TWO ELEMETNS AFTER ONE.
 * 
 * SO HERE BASICALLY ACCESS IS FASTER HOW?
 * ANS : AS WE KNOW SKIPLIST STORES ELEMENTS IN SORTED MANNER AND LAYERED SO HERE IF YOU WAN TO FETCH THE ELEMENT 2 THEN THAT WILL GO INTO LAYER 3 WHERE IT CHECKS
 * WITH INITIAL ELEMENT THAT IS 1 AND NOT EQUAL AFTER THIS WILL GO FOR NEXT INDEXT WHERE 5 IS STORED SO THE LOOP BREAKS HERE AS 5 IS GREATER THEN THE 2, AFTER THIS
 * MOVED TO TE LAYER 2 THERE ALSO SAME LOGIC APPLIED NOT FIND AT INDEX 1 AS IT HAVE VALUE 1 THEN NEXT INDEX THAT HAVE 3 WHICH IS GREATER THAN, SO NEXT LAYER INDEX 1
 * THAT CONSIST 1 NEXT INDEX WHERE IT FINDS VALUE 2 EQULS 2 RETURN TRUE.
 * 
 * QUESTION : WE HAVE TREEMAP DATA STRUCTURE WHICH HAVE SELF BALANCED BINARY SEARCH TREE THEN WHY THIS SKIPLIST?
 * ANS : TO MANAGE SELF BALANCED BINARY SEARCH TREE WE NEED COMPLEX ALGORITHMS. HERE THOSE KIND OF ALGORITHMS ARE NOT REQUIRED, AS STRICTNESS IS NOT HERE.
 * 
 * HERE CONCURRENT SKIPLIST MAP MEANS THE KEY VALUE PAIRES WILL BE STORED INTO THE SKIPLIST DATASTRUCTURE.
 */
public class ConcurrentSkipLisrMap_Class {
	public static void main(String[] args) {
		
		/*Here ConcurrentSkipListMap is extends the AbstractMap class and then AbstractMap class which again implements the Map interface
		 * also ConcurrentSkipListMap is implements ConcurrentNavigableMap interface which again extends with two interfaces 
		 * 	1) ConcurrentMap -> Map (interface)
		 *  2) NavigableMap -> SortedMap (interface) -> SequencedMap (interface) -> Map (interface)
		 *  
		 *  
		 *  we can use this in multi-threaded environment.
		 */
		ConcurrentSkipListMap<Integer, String> cslm = new ConcurrentSkipListMap<>();
		
	}

}
